### ISSUE TITLE
[Bug?]: 好友邀请中的验证消息字段无内容

### ISSUE THREAD

**Issue by Xiangze-Li** [LagrangeDev/Lagrange.Core#140]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

46fc168

### 运行环境

Linux

### 运行架构

x64

### 连接方式

正向 WebSocket

### 重现步骤

将机器人的加好友方式设定为验证消息, 向机器人发送好友邀请, 填写一定的验证消息

### 期望的结果是什么？

收到的好友请求中 `comment` 字段正确被填写

### 实际的结果是什么？

为空. 以下是我收到的请求. 

```
{"user_id":X,"request_type":"friend","comment":"","flag":"X","time":1709540095,"self_id":X,"post_type":"request"}
```

### 日志记录（可选）

```Shell
info: Lagrange.OneBot.Core.Notify.NotifyService[0]
      [16:14:55] [FriendRequestEvent]: 1467863771:Kal'tsit 请求添加你为好友
warn: Lagrange.Core.BotContext[0]
      [2024-03-04 16:14:59] [BusinessContext] [WARNING]: Error when processing the event: Lagrange.Core.Internal.Event.Message.ImageUploadEvent
warn: Lagrange.Core.BotContext[0]
      [2024-03-04 16:14:59] [BusinessContext] [WARNING]: Object reference not set to an instance of an object.
warn: Lagrange.Core.BotContext[0]
      [2024-03-04 16:14:59] [BusinessContext] [WARNING]:    at Lagrange.Core.Internal.Service.Message.ImageUploadService.Parse(Byte[] input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, ImageUploadEvent& output, List`1& extraEvents) in D:\a\Lagrange.Core\Lagrange.Core\Lagrange.Core\Internal\Service\Message\ImageUploadService.cs:line 125
         at Lagrange.Core.Internal.Service.BaseService`1.Lagrange.Core.Internal.Service.IService.Parse(Byte[] input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, ProtocolEvent& output, List`1& extraEvents) in D:\a\Lagrange.Core\Lagrange.Core\Lagrange.Core\Internal\Service\BaseService.cs:line 26
         at Lagrange.Core.Internal.Context.ServiceContext.ResolveEventByPacket(SsoPacket packet) in D:\a\Lagrange.Core\Lagrange.Core\Lagrange.Core\Internal\Context\ServiceContext.cs:line 103
         at Lagrange.Core.Internal.Context.BusinessContext.SendEvent(ProtocolEvent event) in D:\a\Lagrange.Core\Lagrange.Core\Lagrange.Core\Internal\Context\BusinessContext.cs:line 105
fail: Lagrange.Core.BotContext[0]
      [2024-03-04 16:14:59] [HighwayContext] [FATAL]: Upload resources for ImageEntity failed
Unknown Event0x210 message type: 35: 0A6F0A4008EBC5D7AF0A1218755F46506C684E4F78424D396C615371736E7A35414C6D5128EBC5D7AF0A3218755F46506C684E4F78424D396C615371736E7A35414C6D5112210890041023182320B3D13D288BAF9A800230848696AF0660B3D1BD8080808080021A080A0012041A020800180122320A0B32312E32382E3131312E3610FE9D011A1F109004188BAF9A800220B3D1BD8080808080023023380140EBC5D7AF0A4801
Unknown Event0x210 message type: 68: 0A97010A4008EBC5D7AF0A1218755F46506C684E4F78424D396C615371736E7A35414C6D5128EBC5D7AF0A3218755F46506C684E4F78424D396C615371736E7A35414C6D5112210890041044184420DBB73B288CAF9A800230848696AF0660DBB7BB8080808080021A300A00122C1A220A18755F46506C684E4F78424D396C615371736E7A35414C6D5110848696AF0618012A0608848696AF06
Unknown Event0x210 message type: 179: 0AC8010A4308DBA5F7BB051218755F594555507778656D334B7067763552674E7A61302D4118E90728EBC5D7AF0A3218755F46506C684E4F78424D396C615371736E7A35414C6D51122308900410B30118B30120E68DF9930328AD8B0330848696AF0660E68DF99383808080021A5C0A001258080112540A18755F594555507778656D334B7067763552674E7A61302D4110001D0483E5652209E587AFE5B094E5B88C2A084B616C2774736974300038004A18755F594555507778656D334B7067763552674E7A61302D41180122340A0E33302E3136392E3132352E32303510FE9D011A1E10900418AD8B0320E68DF993838080800230B301380140DBA5F7BB054801
Unknown Event0x210 message type: FriendPokeNotice: 0AF0010A4008DBA5F7BB051218755F594555507778656D334B7067763552674E7A61302D4128EBC5D7AF0A3218755F46506C684E4F78424D396C615371736E7A35414C6D51122108900410A20218A20220ECFC91F205280130848696AF0660ECFC91F285808080021A88010A0012830110D34F180730F54F42683C6774697020616C69676E3D2263656E746572223E3C6E6F72207478743D22E4BDA0E4BBACE5B7B2E68890E58A9FE6B7BBE58AA0E4B8BAE5A5BDE58F8BEFBC8CE78EB0E59CA8E58FAFE4BBA5E5BC80E5A78BE8818AE5A4A9E4BA86EFBC81222F3E3C2F677469703E509EB9E38703A20608301540DBA5F7BB05180122300A0C32312E32312E3137372E323010FE9D011A1C109004180120ECFC91F2858080800230A202380140DBA5F7BB054801
Unknown Event0x210 message type: 35: 0ABD010A4008DBA5F7BB051218755F594555507778656D334B7067763552674E7A61302D4128EBC5D7AF0A3218755F46506C684E4F78424D396C615371736E7A35414C6D51122008900410231823208FB1C38F0528D20E30848696AF06608FB1C38F85808080021A570A00125312510A18755F46506C684E4F78424D396C615371736E7A35414C6D51180320FF8596AF062A0BE69DA5E887AA5151E7BEA43A0042004A0052001218755F594555507778656D334B7067763552674E7A61302D41180122300A0C33302E34362E35392E31383210FE9D011A1C10900418D20E208FB1C38F85808080023023380140DBA5F7BB054801
Unknown Event0x210 message type: 68: 0ABC010A4308EBC5D7AF0A1218755F46506C684E4F78424D396C615371736E7A35414C6D5118E90728EBC5D7AF0A3218755F46506C684E4F78424D396C615371736E7A35414C6D51121F0890041044184420F7C5D05B28C41430848696AF0660F7C5D0DB80808080021A540A0012500A4E0A18755F46506C684E4F78424D396C615371736E7A35414C6D51180320FF8596AF06280130D40F380B4209E587AFE5B094E5B88C1218755F594555507778656D334B7067763552674E7A61302D41
info: Lagrange.OneBot.Core.Notify.NotifyService[0]
      [16:15:04] [FriendRequestEvent]: 2784355051:
```

**Comment by Linwenxuan05** [comment]
好友邀请至群聊还是好友申请

**Comment by Xiangze-Li** [comment]
> 好友邀请至群聊还是好友申请

加好友

**Comment by Linwenxuan05** [comment]
Fixed at 66d8875dba406f71d89a226b011b452fbe54c248
