### ISSUE TITLE
[Bug?]: OneBot 端无法正确处理合并转发内消息解析

### ISSUE THREAD

**Issue by AkulaKirov** [LagrangeDev/Lagrange.Core#146]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

5073ddf

### 运行环境

Windows

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

向 `send_group_forward_msg` 接口发送如下 json 请求 (已脱敏)

```
{
    "action": "send_group_forward_msg",
    "echo": 1,
    "params": {
        "group_id": xxx,
        "messages": [
            {
                "data": {
                    "name": "xxx",
                    "uin": "xxx",
                    "content": [
                        {
                            "data": {
                                "text": "111"
                            },
                            "type": "text"
                        }
                    ]
                },
                "type": "node"
            },
            {
                "data": {
                    "name": "xxx",
                    "uin": "xxx",
                    "content": [
                        {
                            "data": {
                                "file": "xxx"
                            },
                            "type": "image"
                        }
                    ]
                },
                "type": "node"
            }
        ]
    }
}
```

### 期望的结果是什么？

合并转发消息内的文字以及图片能够被正常发送和显示

### 实际的结果是什么？

除了文字以外的其他消息端均无法显示

显示为 `[该消息类型暂不支持查看]`

### 日志记录（可选）

```Shell
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[2]
      [ReverseWSService] Receive: {"action":"send_group_forward_msg","echo":1,"params":{"group_id":xxx,"messages":[{"data":{"name":"xxx","uin":"xxx","content":[{"data":{"text":"111"},"type":"text"}]},"type":"node"},{"data":{"name":"xxx","uin":"xxx","content":[{"data":{"file":"xxx"},"type":"image"}]},"type":"node"}]}}
trce: Lagrange.Core.BotContext[0]
      [2024-03-06 03:07:08] [ServiceContext] [DEBUG]: Outgoing SSOFrame: trpc.group.long_msg_interface.MsgService.SsoSendLongMsg
trce: Lagrange.Core.BotContext[0]
      [2024-03-06 03:07:08] [ServiceContext] [DEBUG]: Incoming SSOFrame: trpc.group.long_msg_interface.MsgService.SsoSendLongMsg
trce: Lagrange.Core.BotContext[0]
      [2024-03-06 03:07:08] [ServiceContext] [DEBUG]: Outgoing SSOFrame: trpc.group.long_msg_interface.MsgService.SsoRecvLongMsg
warn: Lagrange.Core.BotContext[0]
      [2024-03-06 03:07:08] [BusinessContext] [WARNING]: Error when processing the event: Lagrange.Core.Internal.Event.Message.MultiMsgDownloadEvent
warn: Lagrange.Core.BotContext[0]
      [2024-03-06 03:07:08] [BusinessContext] [WARNING]: Object reference not set to an instance of an object.
warn: Lagrange.Core.BotContext[0]
      [2024-03-06 03:07:08] [BusinessContext] [WARNING]:    at Lagrange.Core.Message.Entity.ImageEntity.Lagrange.Core.Message.IMessageEntity.UnpackElement(Elem elems) in /App/Lagrange.Core/Message/Entity/ImageEntity.cs:line 124
         at Lagrange.Core.Message.MessagePacker.Parse(PushMsgBody message, Boolean isFake) in /App/Lagrange.Core/Message/MessagePacker.cs:line 135
         at Lagrange.Core.Internal.Service.Message.MultiMsgDownloadService.<>c.<Parse>b__1_0(PushMsgBody x) in /App/Lagrange.Core/Internal/Service/Message/MultiMsgDownloadService.cs:line 49
         at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
         at System.Linq.Enumerable.SelectListIterator`2.ToList()
         at Lagrange.Core.Internal.Service.Message.MultiMsgDownloadService.Parse(Byte[] input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, MultiMsgDownloadEvent& output, List`1& extraEvents) in /App/Lagrange.Core/Internal/Service/Message/MultiMsgDownloadService.cs:line 49
         at Lagrange.Core.Internal.Service.BaseService`1.Lagrange.Core.Internal.Service.IService.Parse(Byte[] input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, ProtocolEvent& output, List`1& extraEvents) in /App/Lagrange.Core/Internal/Service/BaseService.cs:line 26
         at Lagrange.Core.Internal.Context.ServiceContext.ResolveEventByPacket(SsoPacket packet) in /App/Lagrange.Core/Internal/Context/ServiceContext.cs:line 103
         at Lagrange.Core.Internal.Context.BusinessContext.SendEvent(ProtocolEvent event) in /App/Lagrange.Core/Internal/Context/BusinessContext.cs:line 105
trce: Lagrange.Core.BotContext[0]
      [2024-03-06 03:07:08] [ServiceContext] [DEBUG]: Outgoing SSOFrame: MessageSvc.PbSendMsg
trce: Lagrange.Core.BotContext[0]
      [2024-03-06 03:07:09] [ServiceContext] [DEBUG]: Incoming SSOFrame: MessageSvc.PbSendMsg
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[1]
      [ReverseWSService] Send: {"status":"ok","retcode":0,"data":{"message_id":214697424,"forward_id":"wj/5l/cR\u002BQW\u002BEPXmelV1\u002BoEz3dnOppoMd6R\u002B7fJFQ62Ox1p1QK8t/biZSybJpUt1"},"echo":1}
trce: Lagrange.Core.BotContext[0]
      [2024-03-06 03:07:09] [ServiceContext] [DEBUG]: Incoming SSOFrame: trpc.msg.olpush.OlPushService.MsgPush
trce: Lagrange.Core.BotContext[0]
      [2024-03-06 03:07:09] [ServiceContext] [DEBUG]: Outgoing SSOFrame: trpc.group.long_msg_interface.MsgService.SsoRecvLongMsg
warn: Lagrange.Core.BotContext[0]
      [2024-03-06 03:07:09] [BusinessContext] [WARNING]: Error when processing the event: Lagrange.Core.Internal.Event.Message.MultiMsgDownloadEvent
warn: Lagrange.Core.BotContext[0]
      [2024-03-06 03:07:09] [BusinessContext] [WARNING]: Object reference not set to an instance of an object.
warn: Lagrange.Core.BotContext[0]
      [2024-03-06 03:07:09] [BusinessContext] [WARNING]:    at Lagrange.Core.Message.Entity.ImageEntity.Lagrange.Core.Message.IMessageEntity.UnpackElement(Elem elems) in /App/Lagrange.Core/Message/Entity/ImageEntity.cs:line 124
         at Lagrange.Core.Message.MessagePacker.Parse(PushMsgBody message, Boolean isFake) in /App/Lagrange.Core/Message/MessagePacker.cs:line 135
         at Lagrange.Core.Internal.Service.Message.MultiMsgDownloadService.<>c.<Parse>b__1_0(PushMsgBody x) in /App/Lagrange.Core/Internal/Service/Message/MultiMsgDownloadService.cs:line 49
         at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
         at System.Linq.Enumerable.SelectListIterator`2.ToList()
         at Lagrange.Core.Internal.Service.Message.MultiMsgDownloadService.Parse(Byte[] input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, MultiMsgDownloadEvent& output, List`1& extraEvents) in /App/Lagrange.Core/Internal/Service/Message/MultiMsgDownloadService.cs:line 49
         at Lagrange.Core.Internal.Service.BaseService`1.Lagrange.Core.Internal.Service.IService.Parse(Byte[] input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, ProtocolEvent& output, List`1& extraEvents) in /App/Lagrange.Core/Internal/Service/BaseService.cs:line 26
         at Lagrange.Core.Internal.Context.ServiceContext.ResolveEventByPacket(SsoPacket packet) in /App/Lagrange.Core/Internal/Context/ServiceContext.cs:line 103
         at Lagrange.Core.Internal.Context.BusinessContext.SendEvent(ProtocolEvent event) in /App/Lagrange.Core/Internal/Context/BusinessContext.cs:line 105
```

### 补充说明（可选）

该问题是由于 [SendGroupForwardOperation](https://github.com/LagrangeDev/Lagrange.Core/blob/master/Lagrange.OneBot/Core/Operation/Message/SendGroupForwardOperation.cs) 内未能正确处理伪造合并转发节点所导致的

参见 Lagrange.Core 内对 `MultiMsgEntity` 的解析

https://github.com/LagrangeDev/Lagrange.Core/blob/5073ddf6658b9be5c27c9ee1c73eefae166ccc4d/Lagrange.Core/Internal/Context/Logic/Implementation/MessagingLogic.cs#L301-L318

注意到逻辑中包含了对合并转发内 `MessageChain` 的解析 (L303-L308) 而 `SendGroupForwardOperation` 内未包含此逻辑

有理由相信相同问题也会发送在 `send_private_forward_msg` 接口

**Comment by ishkong** [comment]
https://github.com/LagrangeDev/Lagrange.Core/commit/3ef721d5fa9ce8f239eba426afa94656592cfb72
