### ISSUE TITLE
[Bug]: 对机器人私聊自发消息引用回复，收到的reply `id`为空

### ISSUE THREAD

**Issue by lava081** [LagrangeDev/Lagrange.Core#272]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

42574843c4d66176fe78d800784514c66a749701

### 运行环境

Windows

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

在私聊中引用一条机器人的**自发消息**进行回复

### 期望的结果是什么？

```
{
    "type": "reply",
    "data": {
        "id": "123456"
    }
}
```

### 实际的结果是什么？

```
{
    "type": "reply",
    "data": {
        "id": "0"
    }
}
```

**Comment by lava081** [comment]
#273 之后，在群聊中引用机器人的自发消息回复，则收不到整条消息
错误日志：
```
info: Lagrange.Core.BotContext[0]
      [2024-04-02 09:53:13] [MessagingLogic] [VERBOSE]: [MessageChain(646247164)(1902688707)] [Forward]: Sequence: 38294 | [Text]:   | [Text]: 1
fail: Lagrange.Core.BotContext[0]
      [2024-04-02 09:53:13] [EventInvoker] [EXCEPTION]:    at LiteDB.Reflection.CreateInstance(Type type)
         at LiteDB.BsonMapper.DeserializeList(Type type, BsonArray value)
         at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
         at LiteDB.BsonMapper.DeserializeObject(EntityMapper entity, Object obj, BsonDocument value)
         at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
         at LiteDB.BsonMapper.DeserializeList(Type type, BsonArray value)
         at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
         at LiteDB.BsonMapper.DeserializeObject(EntityMapper entity, Object obj, BsonDocument value)
         at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
         at LiteDB.LiteQueryable`1.<ToEnumerable>b__27_2(BsonDocument x)
         at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
         at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
         at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
         at LiteDB.LiteCollection`1.FindById(BsonValue id)
         at Lagrange.OneBot.Message.Entity.ReplySegment.FromEntity(MessageChain chain, IMessageEntity entity)
         at Lagrange.OneBot.Message.MessageService.Convert(MessageChain chain)
         at Lagrange.OneBot.Message.MessageService.ConvertToGroupMsg(UInt32 uin, MessageChain chain)
         at Lagrange.OneBot.Message.MessageService.OnGroupMessageReceived(BotContext bot, GroupMessageEvent e)
         at Lagrange.Core.Event.EventInvoker.<>c__DisplayClass3_0.<.ctor>b__7(GroupMessageEvent e)
         at Lagrange.Core.Event.EventInvoker.<>c__DisplayClass5_0.<PostEvent>b__0()
Failed to create instance for type 'Lagrange.Core.Message.MessageChain' from assembly 'Lagrange.Core.Message.MessageChain, Lagrange.Core, Version=0.2.1.0, Culture=neutral, PublicKeyToken=null'. Checks if the class has a public constructor with no parameters.
```

**Comment by Linwenxuan05** [comment]
已经查明问题 储存的sequence和他吗腾讯返回的sequence不一样

**Comment by InariInDream** [comment]
> #273 之后，在群聊中引用机器人的自发消息回复，则收不到整条消息 错误日志：
> 
> ```
> info: Lagrange.Core.BotContext[0]
>       [2024-04-02 09:53:13] [MessagingLogic] [VERBOSE]: [MessageChain(646247164)(1902688707)] [Forward]: Sequence: 38294 | [Text]:   | [Text]: 1
> fail: Lagrange.Core.BotContext[0]
>       [2024-04-02 09:53:13] [EventInvoker] [EXCEPTION]:    at LiteDB.Reflection.CreateInstance(Type type)
>          at LiteDB.BsonMapper.DeserializeList(Type type, BsonArray value)
>          at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
>          at LiteDB.BsonMapper.DeserializeObject(EntityMapper entity, Object obj, BsonDocument value)
>          at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
>          at LiteDB.BsonMapper.DeserializeList(Type type, BsonArray value)
>          at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
>          at LiteDB.BsonMapper.DeserializeObject(EntityMapper entity, Object obj, BsonDocument value)
>          at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
>          at LiteDB.LiteQueryable`1.<ToEnumerable>b__27_2(BsonDocument x)
>          at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
>          at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
>          at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
>          at LiteDB.LiteCollection`1.FindById(BsonValue id)
>          at Lagrange.OneBot.Message.Entity.ReplySegment.FromEntity(MessageChain chain, IMessageEntity entity)
>          at Lagrange.OneBot.Message.MessageService.Convert(MessageChain chain)
>          at Lagrange.OneBot.Message.MessageService.ConvertToGroupMsg(UInt32 uin, MessageChain chain)
>          at Lagrange.OneBot.Message.MessageService.OnGroupMessageReceived(BotContext bot, GroupMessageEvent e)
>          at Lagrange.Core.Event.EventInvoker.<>c__DisplayClass3_0.<.ctor>b__7(GroupMessageEvent e)
>          at Lagrange.Core.Event.EventInvoker.<>c__DisplayClass5_0.<PostEvent>b__0()
> Failed to create instance for type 'Lagrange.Core.Message.MessageChain' from assembly 'Lagrange.Core.Message.MessageChain, Lagrange.Core, Version=0.2.1.0, Culture=neutral, PublicKeyToken=null'. Checks if the class has a public constructor with no parameters.
> ```

请问有这个pr之前的build版本吗，actions里面这个点之前的Artifacts都expired了
最近想开发用引用消息（回复）触发的一个插件，报错后找到这里了
