### ISSUE TITLE
onebot项目在发送图片时读取的path路径错误导致退出进程

### ISSUE THREAD

**Issue by Rod-fish** [LagrangeDev/Lagrange.Core#29]
十分感谢开发者对onebot的支持

错误内容：onebot项目在发送图片时读取的图片路径是从Lagrange.OneBot的目录开始，而发送的图片目录是从根目录开始，导致图片无法读取退出进程

系统环境：Ubuntu22.04
错误日志：

```
trce: Lagrange.OneBot.LagrangeApp[0]
      [ReverseWSService] Receive: {"action": "send_msg", "params": {"user_id": *********, "group_id": **********, "message_type": "group", "message": [{"type": "at", "data": {"qq": "*********"}}, {"type": "text", "data": {"text": " "}}, {"type": "image", "data": {"file": "file:///home/my/bot/zhenxun_bot/resources/image/sign/today_card/********_sign_2023-10-19.png", "type": null, "cache": "true", "proxy": "true", "timeout": null}}]}, "echo": "1"}
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/my/bot/Lagrange.Core/Lagrange.OneBot/home/my/bot/zhenxun_bot/resources/image/sign/today_card/**********_sign_2023-10-19.png'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at Lagrange.OneBot.Core.Message.Entity.ImageSegment.Build(MessageBuilder builder, ISegment segment) in /home/my/bot/Lagrange.Core/Lagrange.OneBot/Core/Message/Entity/ImageSegment.cs:line 34
   at Lagrange.OneBot.Core.Operation.Message.SendMessageOperation.ParseChain(OneBotMessage message) in /home/my/bot/Lagrange.Core/Lagrange.OneBot/Core/Operation/Message/SendMessageOperation.cs:line 53
   at Lagrange.OneBot.Core.Operation.Message.SendMessageOperation.HandleOperation(String echo, BotContext context, JsonObject payload) in /home/my/bot/Lagrange.Core/Lagrange.OneBot/Core/Operation/Message/SendMessageOperation.cs:line 35
   at Lagrange.OneBot.Core.Operation.OperationService.HandleOperation(String data) in /home/my/bot/Lagrange.Core/Lagrange.OneBot/Core/Operation/OperationService.cs:line 38
   at Lagrange.OneBot.Core.Operation.OperationService.<.ctor>b__3_0(Object _, MsgRecvEventArgs e) in /home/my/bot/Lagrange.Core/Lagrange.OneBot/Core/Operation/OperationService.cs:line 28
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   ```
   
Lagrange.OneBot项目和onebot项目同时一台机器上运行
图片路径在'/home/my/bot/zhenxun_bot/resources/image/sign/today_card/*'下，实际上只要发送图片都会先从Lagrange.OneBot目录往下读取，然后出现错误退出进程

目前只是在做onebot测试，并没有完全使用，这个问题检查Lagrange.OneBot的文档说明应该是bug
文档位置：https://github.com/botuniverse/onebot-11/blob/master/message/segment.md#%E5%9B%BE%E7%89%87

**Comment by Linwenxuan05** [comment]
Path的解析不小心写错了 有时间马上改

Rod-fish ***@***.***>于2023年10月19日 周四03:09写道：

**Comment by Linwenxuan05** [comment]
Close as Completed
