### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [LagrangeDev/Lagrange.Core#35]
```C#
info: Lagrange.OneBot.LagrangeApp[0]
      [LagrangeWebSvcCollection]: Multi Connection has been configured
trce: Lagrange.OneBot.LagrangeApp[0]
      [ForwardWSService] Send: {"interval":5000,"status":{"app_initialized":true,"app_enabled":true,"app_good":true,"online":true,"good":true},"meta_event_type":"heartbeat","time":1698572749,"self_id":31******89,"post_type":"meta_event"}
Unhandled exception. System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.Logger`1[Lagrange.OneBot.LagrangeApp]' while attempting to activate 'Lagrange.OneBot.Core.Operation.OperationService'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Lagrange.OneBot.LagrangeApp..ctor(IHost host) in D:\a\Lagrange.Core\Lagrange.Core\Lagrange.OneBot\LagrangeApp.cs:line 41
   at Lagrange.OneBot.LagrangeAppBuilder.Build() in D:\a\Lagrange.Core\Lagrange.Core\Lagrange.OneBot\LagrangeAppBuilder.cs:line 91
   at Lagrange.OneBot.Program.Main(String[] args) in D:\a\Lagrange.Core\Lagrange.Core\Lagrange.OneBot\Program.cs:line 18
```

**Comment by Linwenxuan05** [comment]
回家后修 先用上一个Commit

YuYue ***@***.***>于2023年10月29日 周日下午5:49写道：

**Comment by Linwenxuan05** [comment]
Closed as Resolved
