### ISSUE TITLE
[Bug?]: 最新 release 无法发送 MP3 语音，旧一点的版本可以正常发送

### ISSUE THREAD

**Issue by 1umine** [LagrangeDev/Lagrange.Core#351]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

481d281

### 运行环境

Windows

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

使用最新 [release](https://github.com/LagrangeDev/Lagrange.Core/actions/runs/8969272770)  版本发送 MP3 格式语音

### 期望的结果是什么？

成功发送

### 实际的结果是什么？

无法发送成功，报错

### 日志记录（可选）

```Shell
warn: Lagrange.OneBot.Core.Operation.OperationService[0]
      Unexpected error encountered while handling message.
      System.AggregateException: One or more errors occurred. (Thrown an exception while encoding silk.)
       ---> Konata.Codec.Exceptions.EncodeException: Thrown an exception while encoding silk.
         at Konata.Codec.Audio.Codecs.SilkV3Codec.Encoder.Read(Byte[] buffer, Int32 offset, Int32 count)
         at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
         at Konata.Codec.Audio.AudioPipeline.<Start>b__2_0()
         at System.Threading.Tasks.Task`1.InnerInvoke()
         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at Konata.Codec.Audio.AudioPipeline.Start()
         --- End of inner exception stack trace ---
         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
         at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
         at Lagrange.OneBot.Message.Entity.RecordSegment.ConvertFormat(Stream audio, Double& audioTime)
         at Lagrange.OneBot.Message.Entity.RecordSegment.Build(MessageBuilder builder, SegmentBase segment)
         at Lagrange.OneBot.Core.Operation.Message.MessageCommon.BuildMessages(MessageBuilder builder, List`1 segments)
         at Lagrange.OneBot.Core.Operation.Message.MessageCommon.ParseChain(OneBotMessage message)
         at Lagrange.OneBot.Core.Operation.Message.SendMessageOperation.HandleOperation(BotContext context, JsonNode payload)
         at Lagrange.OneBot.Core.Operation.OperationService.HandleOperation(MsgRecvEventArgs e)
```

### 补充说明（可选）

手动转成 silk 后可以发送，但是手机端可以播放，pc 无法播放

使用次新 [release](https://github.com/LagrangeDev/Lagrange.Core/actions/runs/8733847449) 版本则无此问题，可以正常发送，手机PC都能正常播放

**Comment by DarkCWK** [comment]
上游 [Konata.Codec](https://github.com/KonataDev/Konata.Codec) 加载 dll 有问题

**Comment by DarkCWK** [comment]
[Konata.Codec](https://github.com/KonataDev/Konata.Codec) 的版本推送出了点问题, 推迟解决
