### ISSUE TITLE
發送圖片時偶爾會出現 Index Out Of Range

### ISSUE THREAD

**Issue by eric2788** [LagrangeDev/Lagrange.Core#38]
發送;

(圖片nsfw, 不知是否風控問題導致的錯誤？)

```log
[ForwardWSService] Receive: {"action":"send_group_msg","params":{"group_id":123456789,"message":[{"type":"text","data":{"text":"作者: 逆流茶会 "}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"标签: ##原创10000users加入书籤, #オリジナル10000users入り, #逆流茶会"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"大图: https://i.pixiv.cat/img-original/img/2023/06/28/00/00/15/109403330_p0.jpg "}},{"type":"text","data":{"text":"\n"}},{"type":"image","data":{"file":"https://i.pixiv.cat/c/540x540_70/img-master/img/2023/06/28/00/00/15/109403330_p0_master1200.jpg","cache":0}}]},"echo":66}
```

錯誤日誌:

![image](https://github.com/LagrangeDev/Lagrange.Core/assets/6276840/96d3037e-8427-46b9-9a06-51445dae83ba)

```log
         at Lagrange.OneBot.Core.Operation.OperationService.HandleOperation(MsgRecvEventArgs eventArgs) in /App/Lagrange.OneBot/Core/Operation/OperationService.cs:line 73

         at Lagrange.OneBot.Core.Operation.Message.SendGroupMessageOperation.HandleOperation(BotContext context, JsonObject payload) in /App/Lagrange.OneBot/Core/Operation/Message/SendGroupMessageOperation.cs:line 22

         at Lagrange.Core.Internal.Context.Logic.Implementation.OperationLogic.SendMessage(MessageChain chain) in /App/Lagrange.Core/Internal/Context/Logic/Implementation/OperationLogic.cs:line 42

      System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

      Error while handling Lagrange.OneBot.Core.Network.MsgRecvEventArgs: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

         at Lagrange.Core.Internal.Context.BusinessContext.SendEvent(ProtocolEvent event) in /App/Lagrange.Core/Internal/Context/BusinessContext.cs:line 121

         at Lagrange.Core.Internal.Service.Message.SendMessageService.Build(SendMessageEvent input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, BinaryPacket& output, List`1& extraPackets) in /App/Lagrange.Core/Internal/Service/Message/SendMessageService.cs:line 18

         at Lagrange.Core.Internal.Context.ServiceContext.ResolvePacketByEvent(ProtocolEvent protocolEvent) in /App/Lagrange.Core/Internal/Context/ServiceContext.cs:line 65

         at Lagrange.Core.Message.MessagePacker.Build(MessageChain chain, String selfUid) in /App/Lagrange.Core/Message/MessagePacker.cs:line 66

      [2023-11-16 12:10:02] [BusinessContext] [WARNING]:    at Lagrange.Core.Message.Entity.ImageEntity.Lagrange.Core.Message.IMessageEntity.PackElement() in /App/Lagrange.Core/Message/Entity/ImageEntity.cs:line 65

      [2023-11-16 12:10:02] [BusinessContext] [WARNING]: Exception of type 'System.ArgumentOutOfRangeException' was thrown. (Parameter 'type')

      [2023-11-16 12:10:02] [BusinessContext] [WARNING]:    at Lagrange.Core.Internal.Service.Message.ImageGroupUploadService.Build(ImageGroupUploadEvent input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, BinaryPacket& output, List`1& extraPackets) in /App/Lagrange.Core/Internal/Service/Message/ImageGroupUploadService.cs:line 33

      [ForwardWSService] Send: {"status":"failed","retcode":200,"data":"Index was out of range. Must be non-negative and less than the size of the collection. (Parameter \u0027index\u0027)","echo":66}

```

**Comment by Linwenxuan05** [comment]
拉格兰的ImageResolver识别不了发送的图片格式导致炸了，建议先自己从Bot层转一次

**Comment by eric2788** [comment]
> 拉格兰的ImageResolver识别不了发送的图片格式导致炸了，建议先自己从Bot层转一次

轉一次是指?

**Comment by Linwenxuan05** [comment]
> > 拉格兰的ImageResolver识别不了发送的图片格式导致炸了，建议先自己从Bot层转一次
> 
> 轉一次是指?

比如说转换到常用的格式 如jpeg png

**Comment by eric2788** [comment]
我懂了，原因是那個jpg是404 not found，lgr會做處理嗎？還是交給bot那邊做
