### ISSUE TITLE
[Bug]: 扫码登录完成后报错Not enough data to read

### ISSUE THREAD

**Issue by tmdakm** [LagrangeDev/Lagrange.Core#412]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

https://github.com/LagrangeDev/Lagrange.Core/commit/7d0b5c2d21f46de74eb6c83e2e0729fc50499ef1

### 运行环境

Windows

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

下载一份Release里的最新Lagrange.Onebot 然后运行修改配置文件然后扫码登录
或使用Lagrange.Core 运行并扫码登录
登录完成后会出现报错

### 期望的结果是什么？

成功登录

### 实际的结果是什么？

登录完后循环报错

### Trace 级别日志记录（可选）

```Shell
[2024-06-13 21:42:26] [WtExchangeLogic] [INFORMATION]: QrCode State Queried: WaitingForConfirm Uin: qq号
trce: Lagrange.Core.BotContext[0]
      [2024-06-13 21:42:28] [ServiceContext] [DEBUG]: Outgoing SSOFrame: wtlogin.trans_emp
warn: Lagrange.Core.BotContext[0]
      [2024-06-13 21:42:28] [BusinessContext] [WARNING]: Error when processing the event: Lagrange.Core.Internal.Event.Login.TransEmpEvent
warn: Lagrange.Core.BotContext[0]
      [2024-06-13 21:42:28] [BusinessContext] [WARNING]: Not enough data to read, remaining: 11 required: 65547
warn: Lagrange.Core.BotContext[0]
      [2024-06-13 21:42:28] [BusinessContext] [WARNING]:    at Lagrange.Core.Utility.Binary.BinaryPacket.ReadBytes(Int32 count)
         at Lagrange.Core.Utility.Binary.BinaryPacket.ReadString(Prefix flag)
         at Lagrange.Core.Utility.Binary.BinarySerializer.<>c.<.cctor>b__7_19(BinaryPacket body, Prefix prefix)
         at Lagrange.Core.Utility.Binary.BinarySerializer.Deserialize(BinaryPacket body, Type type)
         at Lagrange.Core.Utility.Binary.Tlv.TlvPacker.ReadTlvBodyQrCode(UInt16 cmd, BinaryPacket packet)
         at Lagrange.Core.Utility.Binary.Tlv.TlvPacker.ReadTlvCollections(BinaryPacket payload, Boolean isQrCode)
         at Lagrange.Core.Internal.Packets.Login.WtLogin.Entity.TransEmp12.Deserialize(BinaryPacket packet, State& qrState)
         at Lagrange.Core.Internal.Service.Login.TransEmpService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, TransEmpEvent& output, List`1& extraEvents)
         at Lagrange.Core.Internal.Service.BaseService`1.Lagrange.Core.Internal.Service.IService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, ProtocolEvent& output, List`1& extraEvents)
         at Lagrange.Core.Internal.Context.ServiceContext.ResolveEventByPacket(SsoPacket packet)
         at Lagrange.Core.Internal.Context.BusinessContext.SendEvent(ProtocolEvent event)
trce: Lagrange.Core.BotContext[0]
      [2024-06-13 21:42:30] [ServiceContext] [DEBUG]: Outgoing SSOFrame: wtlogin.trans_emp
warn: Lagrange.Core.BotContext[0]
      [2024-06-13 21:42:30] [BusinessContext] [WARNING]: Error when processing the event: Lagrange.Core.Internal.Event.Login.TransEmpEvent
warn: Lagrange.Core.BotContext[0]
      [2024-06-13 21:42:30] [BusinessContext] [WARNING]: Not enough data to read, remaining: 11 required: 65547
warn: Lagrange.Core.BotContext[0]
      [2024-06-13 21:42:30] [BusinessContext] [WARNING]:    at Lagrange.Core.Utility.Binary.BinaryPacket.ReadBytes(Int32 count)
         at Lagrange.Core.Utility.Binary.BinaryPacket.ReadString(Prefix flag)
         at Lagrange.Core.Utility.Binary.BinarySerializer.<>c.<.cctor>b__7_19(BinaryPacket body, Prefix prefix)
         at Lagrange.Core.Utility.Binary.BinarySerializer.Deserialize(BinaryPacket body, Type type)
         at Lagrange.Core.Utility.Binary.Tlv.TlvPacker.ReadTlvBodyQrCode(UInt16 cmd, BinaryPacket packet)
         at Lagrange.Core.Utility.Binary.Tlv.TlvPacker.ReadTlvCollections(BinaryPacket payload, Boolean isQrCode)
         at Lagrange.Core.Internal.Packets.Login.WtLogin.Entity.TransEmp12.Deserialize(BinaryPacket packet, State& qrState)
         at Lagrange.Core.Internal.Service.Login.TransEmpService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, TransEmpEvent& output, List`1& extraEvents)
         at Lagrange.Core.Internal.Service.BaseService`1.Lagrange.Core.Internal.Service.IService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, ProtocolEvent& output, List`1& extraEvents)
         at Lagrange.Core.Internal.Context.ServiceContext.ResolveEventByPacket(SsoPacket packet)
         at Lagrange.Core.Internal.Context.BusinessContext.SendEvent(ProtocolEvent event)
trce: Lagrange.Core.BotContext[0]
      [2024-06-13 21:42:32] [ServiceContext] [DEBUG]: Outgoing SSOFrame: wtlogin.trans_emp
warn: Lagrange.Core.BotContext[0]
      [2024-06-13 21:42:32] [BusinessContext] [WARNING]: Error when processing the event: Lagrange.Core.Internal.Event.Login.TransEmpEvent
warn: Lagrange.Core.BotContext[0]
      [2024-06-13 21:42:32] [BusinessContext] [WARNING]: Not enough data to read, remaining: 11 required: 65547
warn: Lagrange.Core.BotContext[0]
      [2024-06-13 21:42:32] [BusinessContext] [WARNING]:    at Lagrange.Core.Utility.Binary.BinaryPacket.ReadBytes(Int32 count)
         at Lagrange.Core.Utility.Binary.BinaryPacket.ReadString(Prefix flag)
         at Lagrange.Core.Utility.Binary.BinarySerializer.<>c.<.cctor>b__7_19(BinaryPacket body, Prefix prefix)
         at Lagrange.Core.Utility.Binary.BinarySerializer.Deserialize(BinaryPacket body, Type type)
         at Lagrange.Core.Utility.Binary.Tlv.TlvPacker.ReadTlvBodyQrCode(UInt16 cmd, BinaryPacket packet)
         at Lagrange.Core.Utility.Binary.Tlv.TlvPacker.ReadTlvCollections(BinaryPacket payload, Boolean isQrCode)
         at Lagrange.Core.Internal.Packets.Login.WtLogin.Entity.TransEmp12.Deserialize(BinaryPacket packet, State& qrState)
         at Lagrange.Core.Internal.Service.Login.TransEmpService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, TransEmpEvent& output, List`1& extraEvents)
         at Lagrange.Core.Internal.Service.BaseService`1.Lagrange.Core.Internal.Service.IService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, ProtocolEvent& output, List`1& extraEvents)
         at Lagrange.Core.Internal.Context.ServiceContext.ResolveEventByPacket(SsoPacket packet)
         at Lagrange.Core.Internal.Context.BusinessContext.SendEvent(ProtocolEvent event)
trce: Lagrange.Core.BotContext[0]
      [2024-06-13 21:42:33] [ServiceContext] [DEBUG]: Outgoing SSOFrame: Heartbeat.Alive
trce: Lagrange.Core.BotContext[0]
      [2024-06-13 21:42:34] [ServiceContext] [DEBUG]: Outgoing SSOFrame: wtlogin.trans_emp
warn: Lagrange.Core.BotContext[0]
```
```


### 补充说明（可选）

在Core和Onebot里面都会这样 开启/关闭VPN也尝试过了

**Comment by ssyximmlove** [comment]
发生了同样的问题，更换QQ号后消失

**Comment by xmbhjQAQ** [comment]
同样的问题

**Comment by wling-art** [comment]
同样的问题

**Comment by Linwenxuan04** [comment]
修好了修好了
