### ISSUE TITLE
[Bug?]: 私聊时推送图片消息到服务端报错，群聊可以

### ISSUE THREAD

**Issue by chuanSir123** [LagrangeDev/Lagrange.Core#433]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

839c225

### 运行环境

Windows

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

直接在qq中私聊发送图片，服务端接收不到。

### 期望的结果是什么？

和群聊一样能够正常接收消息

### 实际的结果是什么？

私聊发送图片，服务端接收不到

### Trace 级别日志记录（可选）

```Shell
[2024-07-09 17:22:01] [BusinessContext] [WARNING]: Error while handling msf push: 12 trpc.msg.olpush.OlPushService.MsgPush
trce: Lagrange.Core.BotContext[0]
      [2024-07-09 17:22:01] [BusinessContext] [DEBUG]: 0000004F9EEB635C000000000000000400000029747270632E6D73672E6F6C707573682E4F6C50757368536572766963652E4D73675075736800000004000000000000000AA80100C80102668D01790000033B0AB4060A4108AF83CAC6011218755F48716C3158796F6678306F41767070705A3545574851180128D6F2F6543218755F4D7761437A58646A2D437A686E6A47455864424B3651122D08A601180B2085DDD6F50828DD6530F982B4B406380158899B016085DDD6F5888080800170819B01E001E3E8011ABF050ABC050A27080010F982B4B4061885DDD6F5082000280B300038860140224A0CE5BEAEE8BDAFE99B85E9BB9112D80422D5040A1B3943317D573756354A544A3544365A49325031605A7D482E6A706710FE86051A352F3431363434383934332D3138303339383036342D3439344242413242363734303437414644354343354143304230373130353833227316203131353130313034314342202020202038323831346534393442424132423637343034374146443543433541433042303731303538332E6A7067762F3431363434383934332D3138303339383036342D34393442424132423637343034374146443543433541433042303731303538334128E8073A10494BBA2B674047AFD5CC5AC0B071058340AE0748800852352F3431363434383934332D3138303339383036342D34393442424132423637343034374146443543433541433042303731303538335A040000000062642F6F66667069635F6E65772F3431363434383934332F2F3431363434383934332D3138303339383036342D34393442424132423637343034374146443543433541433042303731303538332F3139383F7465726D3D3235352669735F6F726967696E3D3072642F6F66667069635F6E65772F3431363434383934332F2F3431363434383934332D3138303339383036342D34393442424132423637343034374146443543433541433042303731303538332F3732303F7465726D3D3235352669735F6F726967696E3D307A622F6F66667069635F6E65772F3431363434383934332F2F3431363434383934332D3138303339383036342D34393442424132423637343034374146443543433541433042303731303538332F303F7465726D3D3235352669735F6F726967696E3D3012044A0208001230AA022D9A012A800101C80100F00100F80100900200CA0400D2050808899B0110819B01B2060A0A080800100018002000
warn: Lagrange.Core.BotContext[0]
      [2024-07-09 17:22:01] [BusinessContext] [WARNING]:    at Lagrange.Core.Message.Entity.ImageEntity.Lagrange.Core.Message.IMessageEntity.UnpackElement(Elem elems)
         at Lagrange.Core.Message.MessagePacker.Parse(PushMsgBody message, Boolean isFake)
         at Lagrange.Core.Internal.Service.Message.PushMessageService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, PushMessageEvent& output, List`1& extraEvents)
         at Lagrange.Core.Internal.Service.BaseService`1.Lagrange.Core.Internal.Service.IService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, ProtocolEvent& output, List`1& extraEvents)
         at Lagrange.Core.Internal.Context.ServiceContext.ResolveEventByPacket(SsoPacket packet)
         at Lagrange.Core.Internal.Context.BusinessContext.HandleServerPacket(SsoPacket packet)
warn: Lagrange.Core.BotContext[0]
      [2024-07-09 17:22:01] [BusinessContext] [WARNING]: Object reference not set to an instance of an object.
```

**Comment by ishkong** [comment]
无法复现，请用最新版lgr重试，并提供无法接收到的具体图片以供测试
