### ISSUE TITLE
[Bug?]: 使用data url私聊发送record信息报错但不影响正常发送 且在群聊中无该问题

### ISSUE THREAD

**Issue by WhitePaper233** [LagrangeDev/Lagrange.Core#450]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

Core

### 所使用/依赖的Lagrange项目对应的commit

https://github.com/LagrangeDev/Lagrange.Core/commit/ef6b41b771624ade51b1662cb66d4fd66d5effd5

### 运行环境

Windows

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

使用data:协议私聊发送一段base64编码的audio/wav的信息报错System.ObjectDisposedException: Cannot access a closed Stream. 但信息正常发出

### 期望的结果是什么？

不报错

### 实际的结果是什么？

报错 但消息正常发出

### 简单的复现代码/链接（可选）

```C#
import { Context, h, Schema } from 'koishi'

export const name = 'test'

export interface Config { }

export const Config: Schema<Config> = Schema.object({})

class test {
    constructor(ctx: Context) {
        ctx.command('test').action(async (_) => {
            const data = await ctx.http.get('https://file-examples.com/storage/feedf97377669a777a26bd6/2017/11/file_example_WAV_1MG.wav', { responseType: 'arraybuffer' })
            return h.audio(data, 'audio/wav')
        })
    }
}

export function apply(ctx: Context) {
    ctx.plugin(test)
}
```

### Trace 级别日志记录（可选）

```Shell
warn: Lagrange.OneBot.Core.Operation.OperationService[0]
      Unexpected error encountered while handling message.
      System.ObjectDisposedException: Cannot access a closed Stream.
         at System.IO.MemoryStream.get_Length()
         at Lagrange.Core.Message.Entity.RecordEntity.get_AudioSize()
         at lambda_method157(Closure, Object)
         at LiteDB.BsonMapper.SerializeObject(Type type, Object obj, Int32 depth)
         at LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)
         at LiteDB.BsonMapper.SerializeArray(Type type, IEnumerable array, Int32 depth)
         at LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)
         at LiteDB.BsonMapper.SerializeObject(Type type, Object obj, Int32 depth)
         at LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)
         at LiteDB.BsonMapper.ToDocument(Type type, Object entity)
         at LiteDB.BsonMapper.ToDocument[T](T entity)
         at LiteDB.LiteCollection`1.Insert(BsonValue id, T entity)
         at Lagrange.OneBot.Core.Operation.Message.SendPrivateMessageOperation.HandleOperation(BotContext context, JsonNode payload)
         at Lagrange.OneBot.Core.Operation.OperationService.HandleOperation(MsgRecvEventArgs e)
```

### 补充说明（可选）

但是同样的 在群聊中发送不会导致这个错误

**Comment by WhitePaper233** [comment]
mp3也会出现相同的问题

**Comment by WhitePaper233** [comment]
已在 https://github.com/LagrangeDev/Lagrange.Core/pull/451 中修复
