### ISSUE TITLE
[Bug?]: 无法获取回复消息的message_id

### ISSUE THREAD

**Issue by zhongwen-4** [LagrangeDev/Lagrange.Core#456]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

Core

### 所使用/依赖的Lagrange项目对应的commit

[All] Implemented GroupEssenceEvent (#453)

### 运行环境

Windows

### 运行架构

x64

### 连接方式

正向 WebSocket

### 重现步骤

私聊设置一个命令, 然后随便回复一条消息, 取回复消息的message_id

### 期望的结果是什么？

能取message_id

### 实际的结果是什么？

取不了message_id

### Trace 级别日志记录（可选）

```Shell
[2024-07-24 09:58:18] [MessagingLogic] [VERBOSE]: [MessageChain(2401128923)] [Forward]: Sequence: 18770 | [Text]: 同意
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[2]
      [ReverseWSService] Send(ae6d899b-e5a5-41a5-af8f-162026f165e6): {"message_type":"private","sub_type":"friend","message_id":-358263171,"user_id":2401128923,"message":[{"type":"reply","data":{"id":"0"}},{"type":"text","data":{"text":"\u540C\u610F"}}],"raw_message":"[CQ:reply,id=0]\u540C\u610F","font":0,"sender":{"user_id":2401128923,"nickname":"\u4E07\u4FCA\u8F89","sex":"unknown"},"target_id":551393530,"time":1721786298,"self_id":551393530,"post_type":"message"}
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[3]
      [ReverseWSService] Receive(ae6d899b-e5a5-41a5-af8f-162026f165e6): {"action": "get_msg", "params": {"message_id": 0}, "echo": "6"}
warn: Lagrange.OneBot.Core.Operation.OperationService[0]
      Unexpected error encountered while handling message.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Lagrange.OneBot.Database.MessageRecord.op_Explicit(MessageRecord record)
         at Lagrange.OneBot.Core.Operation.Message.GetMessageOperation.HandleOperation(BotContext context, JsonNode payload)
         at Lagrange.OneBot.Core.Operation.OperationService.HandleOperation(MsgRecvEventArgs e)
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[2]
      [ReverseWSService] Send(ae6d899b-e5a5-41a5-af8f-162026f165e6): {"status":"failed","retcode":200,"data":null,"echo":"6"}
```

**Comment by DarkCWK** [comment]
Same:
https://github.com/LagrangeDev/Lagrange.Core/issues/272
