### ISSUE TITLE
[Bug?]: 正向ws断连导致的报错, 或者是吞消息?

### ISSUE THREAD

**Issue by Cjsah** [LagrangeDev/Lagrange.Core#457]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

latest

### 运行环境

Linux

### 运行架构

x64

### 连接方式

正向 WebSocket

### 重现步骤

第三方 反复连接断开websocket

### 期望的结果是什么？

正常运行, 消息正常处理

### 实际的结果是什么？

虽然没有崩溃, 但没法接收新的消息
```
fail: Lagrange.OneBot.Core.Network.Service.ForwardWSService[995]
      ReceiveException(38b43a8d-9325-4992-9238-36f04f205b12)
      System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
       ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
       ---> System.Net.Sockets.SocketException (104): Connection reset by peer
         --- End of inner exception stack trace ---
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
         at System.IO.Stream.ReadAtLeastAsyncCore(Memory`1 buffer, Int32 minimumBytes, Boolean throwOnEndOfStream, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
         at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
         at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
      --- End of stack trace from previous location ---
         at Lagrange.OneBot.Core.Network.Service.ForwardWSService.ReceiveAsyncLoop(String identifier, CancellationToken token)
�fail: Lagrange.OneBot.Core.Network.Service.ForwardWSService[992]
      LogDisconnectException(38b43a8d-9325-4992-9238-36f04f205b12)
      System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived, CloseSent'
         at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
         at System.Net.WebSockets.ManagedWebSocket.CloseAsync(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)
      --- End of stack trace from previous location ---
         at Lagrange.OneBot.Core.Network.Service.ForwardWSService.DisconnectAsync(String identifier, WebSocketCloseStatus status, CancellationToken token)
```

### 补充说明（可选）

搜到了一个问题几乎一模一样的反向ws问题: #153

**Comment by Cjsah** [comment]
感觉更像是 #426

**Comment by kKsk03** [comment]
确实疑似有这个问题 不知道和正向ws有没有关系 总之时不时就噶了 过段时间又好了 挺奇怪

**Comment by DarkCWK** [comment]
报错显示连接被对端重置，请配上对端的日志

**Comment by nuym** [comment]
同样遇到了此问题
