### ISSUE TITLE
[Bug?]: get_friend_list命令执行异常

### ISSUE THREAD

**Issue by 0XPYEX0** [LagrangeDev/Lagrange.Core#579]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

https://github.com/LagrangeDev/Lagrange.Core/commit/8363bc726479f174e723377dd0d2a92137767c1c

### 运行环境

Windows

### 运行架构

x64

### 连接方式

正向 WebSocket

### 重现步骤

向`Lagrange`请求`get_friend_list`时即出现Bug，在上一个release版本(已删，找不到commit)中正常

### 期望的结果是什么？

正常执行

### 实际的结果是什么？

key 0 不在字典中

### Trace 级别日志记录（可选）

```Shell
trce: Lagrange.OneBot.Core.Network.Service.ForwardWSService[12]
      Receive(052a7681-1fe8-4b9d-827e-1f54e10aea32) {"action":"get_friend_list","echo":2}
trce: Lagrange.Core.BotContext[0]
      [2024-09-06 19:12:00] [ServiceContext] [DEBUG]: Outgoing SSOFrame: OidbSvcTrpcTcp.0xfd4_1
trce: Lagrange.Core.BotContext[0]
      [2024-09-06 19:12:00] [ServiceContext] [DEBUG]: Incoming SSOFrame: OidbSvcTrpcTcp.0xfd4_1
warn: Lagrange.OneBot.Core.Operation.OperationService[0]
      Unexpected error encountered while handling message.
      System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
         at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
         at Lagrange.Core.Internal.Context.Logic.Implementation.CachingLogic.ResolveFriendsUidAndFriendGroups()
         at Lagrange.Core.Internal.Context.Logic.Implementation.CachingLogic.GetCachedFriends(Boolean refreshCache)
         at Lagrange.OneBot.Core.Operation.Info.GetFriendListOperation.HandleOperation(BotContext context, JsonNode payload)
         at Lagrange.OneBot.Core.Operation.OperationService.HandleOperation(MsgRecvEventArgs e)
trce: Lagrange.OneBot.Core.Network.Service.ForwardWSService[13]
      Send(052a7681-1fe8-4b9d-827e-1f54e10aea32) {"status":"failed","retcode":200,"data":null,"echo":2}
info: Lagrange.OneBot.Core.Network.Service.ForwardWSService[14]
      Disconnect(052a7681-1fe8-4b9d-827e-1f54e10aea32)
```
以上为`Lagrange`异常信息

**Comment by CwkDark** [comment]
fix on #580
