### ISSUE TITLE
[Bug?]: 在 Linux 上通过 Docker 启动超时

### ISSUE THREAD

**Issue by koking0** [LagrangeDev/Lagrange.Core#587]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

c94f72ac70d6adc38ee89215e76bbd137d611be7

### 运行环境

Linux

### 运行架构

x64

### 连接方式

None

### 重现步骤

```
docker run -td -p 8081:8081 -v /www/wwwroot/head-teacher.matrix-studio.top/qq-bot/Lagrange.OneBot/data:/app/data -e UID=0 -e GID=$(id -g) ghcr.io/lagrangedev/lagrange.onebot:edge
```

appsettings.json:
```json
{
    "Logging": {
        "LogLevel": {
            "Default": "Trace",
            "Microsoft": "Warning",
            "Microsoft.Hosting.Lifetime": "Information"
        }
    },
    "SignServerUrl": "https://sign.lagrangecore.org/api/sign",
    "SignProxyUrl": "",
    "MusicSignServerUrl": "",
    "Account": {
        "Uin": 0,
        "Password": "",
        "Protocol": "Linux",
        "AutoReconnect": true,
        "GetOptimumServer": true
    },
    "Message": {
        "IgnoreSelf": true,
        "StringPost": false
    },
    "QrCode": {
        "ConsoleCompatibilityMode": false
    },
    "Implementations": [
        {
            "Type": "ReverseWebSocket",
            "Host": "127.0.0.1",
            "Port": 8081,
            "Suffix": "/onebot/v11/ws",
            "ReconnectInterval": 5000,
            "HeartBeatInterval": 5000,
            "AccessToken": ""
        }
    ]
}
```

### 期望的结果是什么？

能够扫码登录QQ。

### 实际的结果是什么？

docker log:
```
[40m[1m[33mwarn[39m[22m[49m: Lagrange.OneBot.Utility.MusicSigner[0]
MusicSignServer is not available, sign may be failed
[40m[32minfo[39m[22m[49m: Lagrange.OneBot.LagrangeAppBuilder[0]
Indexing in the database...
[40m[32minfo[39m[22m[49m: Lagrange.OneBot.LagrangeAppBuilder[0]
The first indexing of the old database will load the entire database into memory.
[40m[32minfo[39m[22m[49m: Lagrange.OneBot.LagrangeAppBuilder[0]
If this is the first time creating an index for the old database, please restart the application
[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
Application started. Press Ctrl+C to shut down.
[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
Hosting environment: Production
[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
Content root path: /app/data
[40m[32minfo[39m[22m[49m: Lagrange.OneBot.LagrangeApp[0]
Lagrange.OneBot Implementation has started
[40m[32minfo[39m[22m[49m: Lagrange.OneBot.LagrangeApp[0]
Protocol: | 3.2.10-25765
[40m[32minfo[39m[22m[49m: Lagrange.OneBot.LagrangeApp[0]
Session expired or Password not filled in, try to login by QrCode
[40m[32minfo[39m[22m[49m: Lagrange.Core.BotContext[0]
[2024-09-08 05:13:04] [WtExchangeLogic] [INFORMATION]: Connecting Servers...
[40m[32minfo[39m[22m[49m: Lagrange.Core.BotContext[0]
[2024-09-08 05:13:04] [SocketContext] [VERBOSE]: Server: http://120.232.130.13:8080/ Latency: 44
[40m[32minfo[39m[22m[49m: Lagrange.Core.BotContext[0]
[2024-09-08 05:13:04] [SocketContext] [VERBOSE]: Server: http://120.233.18.186:8080/ Latency: 47
[40m[32minfo[39m[22m[49m: Lagrange.Core.BotContext[0]
[2024-09-08 05:13:04] [SocketContext] [VERBOSE]: Server: http://120.241.130.216:8080/ Latency: 48
[40m[32minfo[39m[22m[49m: Lagrange.Core.BotContext[0]
[2024-09-08 05:13:04] [SocketContext] [VERBOSE]: Server: http://120.241.130.195:8080/ Latency: 49
[40m[32minfo[39m[22m[49m: Lagrange.Core.BotContext[0]
[2024-09-08 05:13:04] [SocketContext] [VERBOSE]: Server: http://120.233.17.147:8080/ Latency: 50
[40m[37mtrce[39m[22m[49m: Lagrange.Core.BotContext[0]
[2024-09-08 05:13:05] [ServiceContext] [DEBUG]: Outgoing SSOFrame: wtlogin.trans_emp
[40m[37mtrce[39m[22m[49m: Lagrange.Core.BotContext[0]
[2024-09-08 05:13:14] [ServiceContext] [DEBUG]: Outgoing SSOFrame: Heartbeat.Alive
[40m[37mtrce[39m[22m[49m: Lagrange.Core.BotContext[0]
[2024-09-08 05:13:24] [ServiceContext] [DEBUG]: Outgoing SSOFrame: Heartbeat.Alive
[40m[37mtrce[39m[22m[49m: Lagrange.Core.BotContext[0]
[2024-09-08 05:13:34] [ServiceContext] [DEBUG]: Outgoing SSOFrame: Heartbeat.Alive
[40m[37mtrce[39m[22m[49m: Lagrange.Core.BotContext[0]
[2024-09-08 05:13:44] [ServiceContext] [DEBUG]: Outgoing SSOFrame: Heartbeat.Alive
[40m[37mtrce[39m[22m[49m: Lagrange.Core.BotContext[0]
[2024-09-08 05:13:54] [ServiceContext] [DEBUG]: Outgoing SSOFrame: Heartbeat.Alive
[40m[37mtrce[39m[22m[49m: Lagrange.Core.BotContext[0]
[2024-09-08 05:14:04] [ServiceContext] [DEBUG]: Outgoing SSOFrame: Heartbeat.Alive
[40m[37mtrce[39m[22m[49m: Lagrange.Core.BotContext[0]
[2024-09-08 05:14:14] [ServiceContext] [DEBUG]: Outgoing SSOFrame: Heartbeat.Alive
[40m[37mtrce[39m[22m[49m: Lagrange.Core.BotContext[0]
[2024-09-08 05:14:24] [ServiceContext] [DEBUG]: Outgoing SSOFrame: Heartbeat.Alive
[40m[37mtrce[39m[22m[49m: Lagrange.Core.BotContext[0]
[2024-09-08 05:14:34] [ServiceContext] [DEBUG]: Outgoing SSOFrame: Heartbeat.Alive
[40m[37mtrce[39m[22m[49m: Lagrange.Core.BotContext[0]
[2024-09-08 05:14:44] [ServiceContext] [DEBUG]: Outgoing SSOFrame: Heartbeat.Alive
[40m[1m[33mwarn[39m[22m[49m: Lagrange.Core.BotContext[0]
[2024-09-08 05:14:45] [BusinessContext] [WARNING]: Error when processing the event: Lagrange.Core.Internal.Event.Login.TransEmpEvent
[40m[1m[33mwarn[39m[22m[49m: Lagrange.Core.BotContext[0]
[2024-09-08 05:14:45] [BusinessContext] [WARNING]: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
---> System.TimeoutException: A task was canceled.
---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.Metrics.MetricsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
--- End of inner exception stack trace ---
at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.Send(HttpRequestMessage request)
at Lagrange.OneBot.Utility.OneBotSigner.Sign(String cmd, UInt32 seq, Byte[] body, Byte[]& e, String& t)
at Lagrange.Core.Internal.Packets.SsoPacker.Build(SsoPacket packet, BotAppInfo appInfo, BotDeviceInfo device, BotKeystore keystore, SignProvider signProvider)
at Lagrange.Core.Internal.Context.PacketContext.SendPacket(SsoPacket packet)
at Lagrange.Core.Internal.Context.BusinessContext.SendEvent(ProtocolEvent event)
[40m[37mtrce[39m[22m[49m: Lagrange.Core.BotContext[0]
[2024-09-08 05:14:54] [ServiceContext] [DEBUG]: Outgoing SSOFrame: Heartbeat.Alive
[40m[37mtrce[39m[22m[49m: Lagrange.Core.BotContext[0]
```

**Comment by Lilyltt** [comment]
sign超时,试一下代理

**Comment by koking0** [comment]
> sign超时,试一下代理

代理要怎么配置呀？这块不太懂。

**Comment by RTAkland** [comment]
> > sign超时,试一下代理
> 
> 代理要怎么配置呀？这块不太懂。

就是系统代理，开个梯

**Comment by koking0** [comment]
> > > sign超时,试一下代理
> > 
> > 
> > 代理要怎么配置呀？这块不太懂。
> 
> 就是系统代理，开个梯

okok
