### ISSUE TITLE
请求实现Onebot中的get_friend_list

### ISSUE THREAD

**Issue by IndigoRCS** [LagrangeDev/Lagrange.Core#59]
在使用[Overflow](https://github.com/MrXiaoM/Overflow)连接Lagrange时，由于Lagrange未实现`get_friend_list`而导致`Overflow`完全无法启动

`Overflow`日志中的报错部分如下：
```
2024-01-03 13:32:15 W/Onebot: Request failed: [get_friend_list, echo=2] 
2024-01-03 13:32:15 E/main: Failed to init MiraiConsole.
java.lang.NullPointerException: impl.getFriendList().data must not be null
        at top.mrxiaom.overflow.internal.contact.BotWrapper.updateContacts(BotWrapper.kt:52)
        at top.mrxiaom.overflow.internal.contact.BotWrapper$updateContacts$1.invokeSuspend(BotWrapper.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at top.mrxiaom.overflow.internal.plugin.OverflowCoreAsPlugin$TheLoader.enable(OverflowCoreAsPlugin.kt:155)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:193)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:360)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:512)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:182)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:181)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:59)
```

`Lagrange`中相关日志如下（敏感信息已用星号代替）：
```
trce: Lagrange.OneBot.Core.Network.Service.ForwardWSService[0]
      [ForwardWSService] Receive(Conn: **********): {"action":"get_friend_list","echo":2}
trce: Lagrange.OneBot.Core.Network.Service.ForwardWSService[0]
      [ForwardWSService] Send: {"status":"failed","retcode":404,"data":null,"echo":2}
```

**Comment by Linwenxuan05** [comment]
Implemented https://github.com/LagrangeDev/Lagrange.Core/commit/38bcab03476b7c944e0df12edcd67e6e4abebc0c

**Comment by IndigoRCS** [comment]
非常感谢！
