### ISSUE TITLE
[Bug Report][Onebot] 无法处理Bot是群主的群消息和私聊消息

### ISSUE THREAD

**Issue by ishkong** [LagrangeDev/Lagrange.Core#61]
该问题出现自 Commit#[0c2b764](https://github.com/LagrangeDev/Lagrange.Core/commit/0c2b76471ac0915f27da7b0a2d45c8fef89ecd4b) 后
群聊log
```shell
fail: Lagrange.Core.BotContext[0]
      [2024-01-04 07:07:23] [EventInvoker] [EXCEPTION]:    at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, Byte level, IndexNode last)
         at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, IndexNode last)
         at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
         at LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction)
         at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
         at LiteDB.Engine.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
         at LiteDB.LiteCollection`1.Insert(BsonValue id, T entity)
         at Lagrange.OneBot.Core.Message.MessageService.OnGroupMessageReceived(BotContext bot, GroupMessageEvent e) in D:\a\Lagrange.Core\Lagrange.Core\Lagrange.OneBot\Core\Message\MessageService.cs:line 78
         at Lagrange.Core.Event.EventInvoker.<>c__DisplayClass3_0.<.ctor>b__6(GroupMessageEvent e) in D:\a\Lagrange.Core\Lagrange.Core\Lagrange.Core\Event\EventInvoker.cs:line 24
         at Lagrange.Core.Event.EventInvoker.<>c__DisplayClass4_0`1.<RegisterEvent>b__0(EventBase e) in D:\a\Lagrange.Core\Lagrange.Core\Lagrange.Core\Event\EventInvoker.cs:line 35
         at Lagrange.Core.Event.EventInvoker.<>c__DisplayClass5_0.<PostEvent>b__0() in D:\a\Lagrange.Core\Lagrange.Core\Lagrange.Core\Event\EventInvoker.cs:line 43
      Cannot insert duplicate key in unique index '_id'. The duplicate value is '{"$numberLong":"2021196032"}'.
```
私聊log
```
fail: Lagrange.Core.BotContext[0]
      [2024-01-04 07:09:54] [EventInvoker] [EXCEPTION]:    at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, Byte level, IndexNode last)
         at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, IndexNode last)
         at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
         at LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction)
         at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
         at LiteDB.Engine.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
         at LiteDB.LiteCollection`1.Insert(BsonValue id, T entity)
         at Lagrange.OneBot.Core.Message.MessageService.OnFriendMessageReceived(BotContext bot, FriendMessageEvent e) in D:\a\Lagrange.Core\Lagrange.Core\Lagrange.OneBot\Core\Message\MessageService.cs:line 57
         at Lagrange.Core.Event.EventInvoker.<>c__DisplayClass3_0.<.ctor>b__5(FriendMessageEvent e) in D:\a\Lagrange.Core\Lagrange.Core\Lagrange.Core\Event\EventInvoker.cs:line 23
         at Lagrange.Core.Event.EventInvoker.<>c__DisplayClass4_0`1.<RegisterEvent>b__0(EventBase e) in D:\a\Lagrange.Core\Lagrange.Core\Lagrange.Core\Event\EventInvoker.cs:line 35
         at Lagrange.Core.Event.EventInvoker.<>c__DisplayClass5_0.<PostEvent>b__0() in D:\a\Lagrange.Core\Lagrange.Core\Lagrange.Core\Event\EventInvoker.cs:line 43
      Cannot insert duplicate key in unique index '_id'. The duplicate value is '{"$numberLong":"256"}'.
```

**Comment by Linwenxuan05** [comment]
Fixed 7776924b680831366e231da566a6fd2055a49414
