### ISSUE TITLE
[Bug?]: 私聊发送图片失败

### ISSUE THREAD

**Issue by StarSky919** [LagrangeDev/Lagrange.Core#668]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [x] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

358068777535584a3b1ce31c3082ebdf559fe228

### 运行环境

Linux

### 运行架构

arm64

### 连接方式

正向 WebSocket

### 重现步骤

1.加好友
2.调用接口发送一张图片

### 期望的结果是什么？

图片正常发出

### 实际的结果是什么？

图片发送失败

### Trace 级别日志记录（可选）

```Shell
trce: Lagrange.Core.BotContext[0]
      [2024-11-01 14:06:32] [ServiceContext] [DEBUG]: Outgoing SSOFrame: OidbSvcT rpcTcp.0x11c5_100
warn: Lagrange.Core.BotContext[0]
      [2024-11-01 14:06:33] [BusinessContext] [WARNING]: Error when processing th e event: Lagrange.Core.Internal.Event.Message.ImageUploadEvent
warn: Lagrange.Core.BotContext[0]
      [2024-11-01 14:06:33] [BusinessContext] [WARNING]: System.NullReferenceExce ption: Object reference not set to an instance of an object.
         at Lagrange.Core.Internal.Service.Message.ImageUploadService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, ImageUploadEvent& output, List`1& extraEvents)
         at Lagrange.Core.Internal.Service.BaseService`1.Lagrange.Core.Internal.Service.IService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, ProtocolEvent& output, List`1& extraEvents)
         at Lagrange.Core.Internal.Context.ServiceContext.ResolveEventByPacket(SsoPacket packet)
         at Lagrange.Core.Internal.Context.BusinessContext.SendEvent(ProtocolEvent event)
fail: Lagrange.Core.BotContext[0]
      [2024-11-01 14:06:33] [HighwayContext] [FATAL]: Upload resources for ImageEntity failed
trce: Lagrange.Core.BotContext[0]
      [2024-11-01 14:06:33] [ServiceContext] [DEBUG]: Outgoing SSOFrame: MessageSvc.PbSendMsg
trce: Lagrange.Core.BotContext[0]
      [2024-11-01 14:06:33] [ServiceContext] [DEBUG]: Incoming SSOFrame: MessageSvc.PbSendMsg
trce: Lagrange.OneBot.Core.Network.Service.HttpService[4]
      Send(Conn: 5edf7a73-a81a-4624-93b6-c8fbe917f3bf：{"status":"ok","retcode":0,"data":{"message_id":2653196},"echo":null})
```

### 补充说明（可选）

该问题只出现在近期新添加好友的私聊中，超过一个月前就已经是好友的则无此问题，群聊中无此问题
已确认不是账号原因，使用其他协议库（如NapCat）可以正常发送

**Comment by StarSky919** [comment]
最新构建重新测试，问题已解决
