### ISSUE TITLE
Json serialization exception causes program crash

### ISSUE THREAD

**Issue by NepPure** [LagrangeDev/Lagrange.Core#71]
winserver 系统日志

```log
错误应用程序名称: Lagrange.OneBot.exe，版本: 0.0.1.0，时间戳: 0x65310000
错误模块名称: KERNELBASE.dll，版本: 10.0.17763.3887，时间戳: 0x3e07c6b6
异常代码: 0xe0434352
错误偏移量: 0x00000000000349b9
错误进程 ID: 0x4ea8
错误应用程序启动时间: 0x01da47a4632347b7
错误应用程序路径: C:\Server\Lagrange.OneBot_win-x64\Lagrange.OneBot.exe
错误模块路径: C:\Windows\System32\KERNELBASE.dll
报告 ID: 143af6c6-f1de-4894-800c-3327c59cbda7
错误程序包全名: 
错误程序包相对应用程序 ID: 

```

```log
Application: Lagrange.OneBot.exe
CoreCLR Version: 7.0.1523.57226
.NET Version: 7.0.15
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Lagrange.OneBot.Core.Operation.OperationService.HandleOperation(MsgRecvEventArgs e) in D:\a\Lagrange.Core\Lagrange.Core\Lagrange.OneBot\Core\Operation\OperationService.cs:line 42
   at Lagrange.OneBot.Core.Network.LagrangeWebSvcCollection.<>c__DisplayClass6_1.<<StartAsync>b__0>d.MoveNext() in D:\a\Lagrange.Core\Lagrange.Core\Lagrange.OneBot\Core\Network\LagrangeWebSvcCollection.cs:line 48
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()


```

**Comment by NepPure** [comment]
看了一下监听ws消息反序列化如果异常会导致程序崩溃，是在外面try还是怎么处理比较合理？
