### ISSUE TITLE
[Bug?]:今天中午突然出现这个情况，下午发现qq还在线，但是发消息没反应了，重启后又好了

### ISSUE THREAD

**Issue by zzzdy110** [LagrangeDev/Lagrange.Core#722]
```
2024/12/30 11:33:01	stdout	      Cannot insert duplicate key in unique index '_id'. The duplicate value is '72290585'.
2024/12/30 11:33:01	stdout	         at Lagrange.Core.Event.EventInvoker.<>c__DisplayClass5_0.<PostEvent>b__0()
2024/12/30 11:33:01	stdout	         at Lagrange.Core.Event.EventInvoker.<>c__DisplayClass3_0.<.ctor>b__6(FriendMessageEvent e)
2024/12/30 11:33:01	stdout	         at Lagrange.OneBot.Message.MessageService.OnFriendMessageReceived(BotContext bot, FriendMessageEvent e)
2024/12/30 11:33:01	stdout	         at LiteDB.LiteCollection`1.Insert(BsonValue id, T entity)
2024/12/30 11:33:01	stdout	         at LiteDB.Engine.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
2024/12/30 11:33:01	stdout	         at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
2024/12/30 11:33:01	stdout	         at LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction)
2024/12/30 11:33:01	stdout	         at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
2024/12/30 11:33:01	stdout	      [2024-12-30 03:33:01] [EventInvoker] [EXCEPTION]:    at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, Byte level, IndexNode last)
2024/12/30 11:33:01	stdout	[41m[30mfail[39m[22m[49m: Lagrange.Core.BotContext[0]
```

**Comment by DarkRRb** [comment]
消息 id 撞 hash 了, 无影响, 但此条消息丢失

无法修复
