### ISSUE TITLE
扫码登陆后Unable to connect to the remote server: Connection refused (127.0.0.1:20028)

### ISSUE THREAD

**Issue by Zhou-Shilin** [LagrangeDev/Lagrange.Core#89]
# 描述
扫码登陆后，无限循环输出这段错误：
```
warn: Lagrange.OneBot.Core.Network.Service.ReverseWSService[3]
      [ReverseWSService] Client disconnected
      System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
       ---> System.Net.Http.HttpRequestException: Connection refused (127.0.0.1:20028)
       ---> System.Net.Sockets.SocketException (111): Connection refused
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
         at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken, ClientWebSocketOptions options)
         at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken, ClientWebSocketOptions options)
         at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken)
         at Lagrange.OneBot.Core.Network.Service.ReverseWSService.ExecuteAsync(CancellationToken stoppingToken) in /App/Lagrange.OneBot/Core/Network/Service/ReverseWSService.cs:line 123
```
# 视频
https://github.com/LagrangeDev/Lagrange.Core/assets/86581525/da82cc8f-34a3-4f41-a956-c7d73e1dd545
很抱歉是拍屏（日志在上面已经给出，所以不用看的很清楚，问题应该不大？）

# 完整日志
6600多行，但全是循环…
[logs.txt](http://files.baimoqilin.top:8088/files.baimoqilin.top:8088/d/files/downloads/logs.txt)

# 环境
```
#101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 5.15.0-91-generic
using docker
```

**Comment by DarkCWK** [comment]
无法连接到ws服务器, 请确定有服务开在了 127.0.0.1:20028 端口

**Comment by DarkCWK** [comment]
看了一下还有http和httppost…
你是有四个服务连接lagrange么？

**Comment by caelumlux** [comment]
你反向代理 本地 确定 20028有 服务？
而且http post 和反向ws 连同一个服务的话有一个就行了。

我没记错的话现在拉格兰还不支持http, http post
