### ISSUE TITLE
正向ws断连会导致lagrange崩溃

### ISSUE THREAD

**Issue by zhzhongshi** [LagrangeDev/Lagrange.Core#97]
使用ubuntu 22.04
lgr下的目前最新的actions里的
![image](https://github.com/LagrangeDev/Lagrange.Core/assets/39423408/ee087c10-2293-4280-a26d-a26630560fa7)
采用正向ws 从nb连接到在服务器上的lgr

lgr.log:
```
info: Lagrange.Core.BotContext[0]
      [2024-02-17 13:12:59] [MessagingLogic] [VERBOSE]: [MessageChain(330986863)(1772360572)] [Forward]: Sequence: 3454060 | [Mention]: @再聊二游是傻逼(1935161782) | [Text]:   | [Mention]: @再聊二游是傻逼(1935161782) | [Text]:  斗破大陆
？￿
info: Lagrange.OneBot.Core.Network.Service.ForwardWSService[0]
      [ForwardWSService] Connected(Conn: 29f6742e-6815-4acb-b6ca-56dc8f193038)
info: Lagrange.Core.BotContext[0]
      [2024-02-17 13:13:02] [MessagingLogic] [VERBOSE]: [MessageChain(746562954)(1948263978)] [Text]: 好家伙
warn: Lagrange.OneBot.Core.Network.Service.ForwardWSService[0]
      [ForwardWSService: Disconnected(Conn: 29f6742e-6815-4acb-b6ca-56dc8f193038)
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.EndWrite(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Lagrange.OneBot.Core.Network.Service.ForwardWSService.SendJsonAsync[T](T json, String identifier, CancellationToken cancellationToken) in /root/Lagrange.Core/Lagrange.OneBot/Core/Network/Service/ForwardWSService.cs:line 118
   at Lagrange.OneBot.Core.Network.LagrangeWebSvcCollection.<>c__DisplayClass6_1.<<StartAsync>b__0>d.MoveNext() in /root/Lagrange.Core/Lagrange.OneBot/Core/Network/LagrangeWebSvcCollection.cs:line 50
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2/17/2024 1:13:02 PM [Info] Failed to send. Disconnecting. System.AggregateException: One or more errors occurred. (Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.)
 ---> System.ObjectDisposedException: Cannot access a disAborted (core dumped)
```
lgr的conf：
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "ConfigPath": {
    "Keystore": "./data/keystore.json",
    "DeviceInfo": "./data/device.json",
    "Database":  "./data/Lagrange.db"
  },
  "SignServerUrl": "url2sign",
  "Account": {
    "Uin": 09,
    "Password": "*",
    "Protocol": "Linux",
    "AutoReconnect": true,
    "GetOptimumServer": true
  },
  "Message": {
    "IgnoreSelf": true
  },
  "Implementations": [
    {
      "Type": "ForwardWebSocket",
      "Host": "0.0.0.0",
      "Port": 6700,
      "HeartBeatInterval": 5000,
      "AccessToken": "mytoken"
    }
  ]
}
```

nb2的日志：
这一段循环
```
02-17 15:34:36 [ERROR] nonebot | OneBot V11 | Error while setup websocket to ws://127.0.0.1:6700/. Trying to reconnect...
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/root/bot/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "/root/bot/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 185, in run
    uvicorn.run(
  File "/root/bot/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/root/bot/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/root/bot/.venv/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 331, in _forward_ws
    async with self.websocket(request) as ws:
  File "/usr/lib/python3.10/contextlib.py", line 199, in aenter
    return await anext(self.gen)
  File "/root/bot/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/adapter.py", line 98, in websocket
    async with self.driver.websocket(setup) as ws:
  File "/usr/lib/python3.10/contextlib.py", line 199, in aenter
    return await anext(self.gen)
  File "/root/bot/.venv/lib/python3.10/site-packages/nonebot/drivers/websockets.py", line 74, in websocket
    async with connection as ws:
  File "/root/bot/.venv/lib/python3.10/site-packages/websockets/legacy/client.py", line 629, in aenter
    return await self
  File "/root/bot/.venv/lib/python3.10/site-packages/websockets/legacy/client.py", line 647, in await_impl_timeout
    return await self.await_impl()
  File "/root/bot/.venv/lib/python3.10/site-packages/websockets/legacy/client.py", line 651, in await_impl
    _transport, _protocol = await self._create_connection()
  File "uvloop/loop.pyx", line 2039, in create_connection
    raise exceptions[0]
  File "uvloop/loop.pyx", line 2016, in uvloop.loop.Loop.create_connection
    await waiter
ConnectionRefusedError: [Errno 111] Connection refused
```

nb2的配置：
.env.dev:
```
LOG_LEVEL=DEBUG
DRIVER=~fastapi+~websockets
ONEBOT_WS_URLS=["ws://127.0.0.1:6700/"]
ONEBOT_ACCESS_TOKEN=mytoken
SUPERUSERS=["012"]
```

**Comment by Linwenxuan05** [comment]
Fixed f48f3fcc623a0402223cbe9e09c98efe5c650115

**Comment by zhzhongshi** [comment]
[nb.log](https://github.com/LagrangeDev/Lagrange.Core/files/14322598/nb.log)
[lgr.log](https://github.com/LagrangeDev/Lagrange.Core/files/14322599/lgr.log)
好奇怪
